apiVersion: v1
kind: ConfigMap
metadata:
  name: books-service-config
  namespace: kiran-nagp-ns
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
  books-service-config.msg: Welcome, Hello World
  books-service-config.title: Java Rest App
  books-service-config.db-url: jdbc:postgresql://postgres-0.postgres-db-headless:5432/postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: books-service-secret-config
  namespace: kiran-nagp-ns
  labels:
    app: postgres
data:
  #postgres
  POSTGRES_USER: cG9zdGdyZXM=
  #P@ssw0rd
  POSTGRES_PASSWORD: UEBzc3cwcmQ=
  books-service-secret-config.db-username: cG9zdGdyZXM=
  books-service-secret-config.password: UEBzc3cwcmQ=
