apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: books-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: books-service
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: CPU
      target:
        type: Utilization
        averageUtilization: 2
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 1
      stabilizationWindowSeconds: 5





