apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcp-storage-class
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain   # Retain or Delete
#allowVolumeExpansion: true    # true or false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-disk-pvc
  namespace: kiran-nagp-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gcp-storage-class
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: kiran-nagp-ns
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: books-service-config
            - secretRef:
                name: books-service-secret-config
          volumeMounts:
            - name: gcp-disk-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: gcp-disk-pvc
          persistentVolumeClaim:
            claimName: gcp-disk-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-headless
  namespace: kiran-nagp-ns
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      name: https
      port: 5432
      targetPort: 5432