apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: filestore-example
  resources:
    requests:
      storage: 4Gi