apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: java-hello-world-rs
  labels:
    app: java-hw
spec:
  template:
    metadata:
      name: java-hw
      labels:
        app: java-hw
    spec:
      containers:
        - name: java-hw
          image: kiranbabun/java-hello-world-image:1
          ports:
            - containerPort: 8000
  replicas: 3
  selector:
    matchLabels:
      app: java-hw

