server:
  port: 8000
message: ${books-service-config.msg}
title: ${books-service-config.title}
password: ${books-service-config.password}

spring:
  application:
    name: book-service
  datasource:
    url: ${books-service-config.db-url}
    username: ${books-service-secret-config.db-username}
    password: ${books-service-secret-config.db-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
      properties:
      hibernate:
        default_schema: postgres_db


